# Generated by Django 5.2.12 on 2026-03-24 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_table_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
